openapi: 3.2.0
info:
  title: Authorizer - OpenId Connect Protocol API
  description: 'OpenId Connect API for Authorizer.

    This is needed in between the developer portal and Keycloak since it seems the dev portals HTTP client can''t speak properly directly with Keycloak for some reason.'
  version: '1.0'
servers:
- url: https://api.openservices.cambio.se/auth/realms/COS
security:
- {}
- apiKeyHeader: []
- apiKeyQuery: []
tags:
- name: Protocol
paths:
  /protocol/openid-connect/*:
    get:
      operationId: get-open-id-connect
      summary: GET Open Id Connect
      description: ''
      responses:
        '200':
          description: Successful response
      tags:
      - Protocol
  /protocol/openid-connect/token:
    post:
      operationId: token-endpoint
      summary: Token Endpoint
      responses:
        '200':
          description: 'null'
      tags:
      - Protocol
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
